from ascii_drawing import *

def test_scale_conversor():
    pict = """\
############            llllllllllll@@@@@@@@@@@@..........
############            llllllllllll@@@@@@@@@@@@..........
############            llllllllllll@@@@@@@@@@@@..........
############            llllllllllll@@@@@@@@@@@@..........
############            llllllllllll@@@@@@@@@@@@..........
############            llllllllllll@@@@@@@@@@@@..........
############            llllllllllll@@@@@@@@@@@@..........
            ############llllllllllll@@@@@@@@@@@@..........
            ############llllllllllll@@@@@@@@@@@@..........
            ############llllllllllll@@@@@@@@@@@@..........
            ############llllllllllll@@@@@@@@@@@@..........
            ############llllllllllll@@@@@@@@@@@@..........
            ############llllllllllll@@@@@@@@@@@@..........
            ############llllllllllll@@@@@@@@@@@@..........
"""
    f = figure_from_string(pict)
    h = 14
    w = 58
    assert f.get_height() == h
    assert f.get_width() == w
    sc = ScaleConversor(3 * h, w)
    f2 = sc.convert(f)
    f3 = ScaleConversor(h, 2 * w).convert(f2)
    print f
    print f2
    print f3
    assert repr(f3) == pict

